### ISSUE TITLE
Brand Switch Dialog

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-header#111]
To allow users to switch brands without having to leave their application, we will show a brand selection dialog triggered when a user clicks Switch Brand in the header.

![image](https://cloud.githubusercontent.com/assets/14326547/18700795/9053a706-7fd9-11e6-91bf-f94c1b5c4540.png)

Steps:
- [ ] Integrate ngDialog and use styles + templates from Solution Center for [dress code dialogs](http://zalando.github.io/dress-code/04-molecules.html#07-dialog).
- [ ] Port the brand selection search form out of the Solution Center into the dialog
- [ ] Extend the header API to include fields for `brands` (merchants? business partners?) and `recentBrands`, to be loaded and passed in by consumers. Align with BE on the structure of data that will come from the recent brands API.
- [ ] Update the Switch Brand link to open the new dialog rather than redirecting.
- [ ] Switch the header to load its own data???
- [ ] Persist the brand when changed (via solution-center-login)

See #108 for my research findings. This design fixes #109.

**Comment by cjhowald** [comment]
As discussed with @gregdeane and @frontendherodk today, we need to discuss with header consumers the change to the header loading its own data.

**Comment by cjhowald** [comment]
Putting this design on hold for now - since the stateless to state transition should be considered as a part of the larger solution center 2.0 redesign, in particular the redesign of the header to work with other frameworks.

**Comment by gregdeane** [comment]
To be done in solution-center-navigation.
