### ISSUE TITLE
Add current project version to element

### ISSUE THREAD

**Issue by gregdeane** [zalando-incubator/solution-center-header#118]
In order to quickly determine which version is being used, add a hidden element with a `data-version` property with a value that equals the current version of the product.

For example:
`<span class="hidden" data-version="2.0.1"></span>`

The value should automatically update whenever a release is made.

**Comment by dami-gg** [comment]
Nice idea, moving it to the Solution Center Navigation (https://github.com/zalando-incubator/solution-center-navigation/issues/99)
