### ISSUE TITLE
User and Help icons don't show in Firefox

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-header#126]
In Firefox, the user and help icons are hidden:

![image](https://cloud.githubusercontent.com/assets/14326547/24900605/b03522e2-1ea4-11e7-8e30-ec02bae3c812.png)

In Chrome and Safari, they show correctly:

![image](https://cloud.githubusercontent.com/assets/14326547/24900629/c367c8ba-1ea4-11e7-8272-a9ca88867afc.png)

The issue is that we set the content to the svg via xml, and Firefox parses the xml more strictly than Chrome and Safari. This can be seen by viewing the content source directly in the browser. In Chrome and Safari, the svg icon is rendered. Firefox throws this error:

![image](https://cloud.githubusercontent.com/assets/14326547/24900730/0d49f214-1ea5-11e7-94e2-a01eb993ac14.png)

The root issue is that he colors use `#` which is a reserved xml character. We need to escape it with `%23` instead. See [here](http://stackoverflow.com/questions/30676125/svg-as-data-uri-triggers-xml-parsing-error-in-firefox) for more details.

**Comment by dami-gg** [comment]
We need to check in the navigation as well, since I'm afraid it's going to happen the same

**Comment by cjhowald** [comment]
@dami-gg I just checked the navigation and this issue does not appear there. We are using the standard dc-icon classes rather than setting the svg content directly.
