### ISSUE TITLE
Delay loading the style from nanorep when opening the dialog

### ISSUE THREAD

**Issue by dami-gg** [zalando-incubator/solution-center-header#14]
First time the dialog is opened it's shown without any style while it's being fetched from Nanorep and it totally looks like broken

My suggestion would be to copy the minimal code needed to show a nice style there into our CSS code so we can hide this effect to the user. It's quite small and shouldn't affect the performance at all.

**Comment by gabrielhl** [comment]
+1

On Fri, Apr 8, 2016 at 2:36 PM, Dami <notifications@github.com> wrote:

> First time the dialog is opened it's shown without any style while it's
> being fetched from Nanorep and it totally looks like broken
>
> My suggestion would be to copy the minimal code needed to show a nice
> style there into our CSS code so we can hide this effect to the user. It's
> quite small and shouldn't affect the performance at all.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/zalando/solution-center-header/issues/14>
>



-- 

Gabriel Lovato
Visual Designer / Brand Solutions
Zalando SE

POSTAL ADDRESS
Zalando SE
11501 Berlin

OFFICE
Zalando SE
Mollstraße 1
10178 Berlin
Germany

Fax: +493027594693
Email: gabriel.lovato@zalando.de
Web: corporate.zalando.de
Jobs: jobs.zalando.de

Zalando SE, Tamara-Danz-Straße 1, 10243 Berlin
Company registration: Amtsgericht Charlottenburg, HRB 158855 B
Tax ID: 29/560/00596 * VAT registration number: DE 260543043
Management Board: Robert Gentz, David Schneider, Rubin Ritter
Chairperson of the Supervisory Board: Cristina Stenbeck
Registered office: Berlin

**Comment by cjhowald** [comment]
Fixed by nanorep. Styles now load immediately on page load instead of when the user clicks the help icon. So, when the help icon is clicked, styles are already loaded and there is no FOUC.
