### ISSUE TITLE
chore(releasing): improve releasing process 

### ISSUE THREAD

**Issue by rbarilani** [zalando-incubator/solution-center-header#15]
I suggest to:

* have CHANGELOG to communicate breaking changes, new features, etc.
* use strict usage of semantic versioning

**Comment by dami-gg** [comment]
I agree with the CHANGELOG, I'm adding it now for the new version I've just released

Can you explain better what you mean with the second bullet? I guess it's related with the versioning number but perhaps there's something more I'm missing and we could consider

**Comment by rbarilani** [comment]
@dami-gg yup here: http://semver.org/

**Comment by dami-gg** [comment]
Good, I'll keep this issue open for a while till we define the proper naming Thanks for the tip!
