### ISSUE TITLE
Nanorep Widget too Wide for Smartphones

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-header#2]
The nanorep widget is fixed at width 400px. In a smartphone viewport (e.g. 320px), it does not display well:

![image](https://cloud.githubusercontent.com/assets/14326547/13497303/e572832a-e154-11e5-9992-92e66f506bc7.png)

We should either attempt to resize dynamically when at smaller widths using @media (this may not be possible since the nanorep widget expects a fixed width in its API) or use a smaller fixed with (e.g. 320px) that works on most smartphones.

**Comment by dami-gg** [comment]
@gabrielhl any input on that topic?

**Comment by dami-gg** [comment]
same for @gloriarupprecht Welcome to Zalando incubator ;)

**Comment by gabrielhl** [comment]
@dami-gg I think @cjhowald is right that the first thing should be to see if we can pass different values to the Nanorep tool depending on whether it's mobile or desktop. Alternatively with some JS you can probably even send the actual viewport size on mobile, so the widget will always fills the screen. What do you think?
The last resort would be to do 320px for desktop and mobile, but it would be less than ideal for desktop users (the window is already small at 400)

**Comment by frontendherodk** [comment]
Awaiting response from Nanorep regarding styles on mobile.

**Comment by cjhowald** [comment]
Fixed by nanorep with latest release.
