### ISSUE TITLE
Update Logo to New Zalando Logo

### ISSUE THREAD

**Issue by dami-gg** [zalando-incubator/solution-center-header#20]
To comply with Zalando's new CI, the logo in the header must be changed
The new logo in SVG format is attached to the issue
[logo.svg.zip](https://github.com/zalando-incubator/solution-center-header/files/246892/logo.svg.zip)

**Comment by sambhav-gore** [comment]
Closed in https://github.com/zalando-incubator/solution-center-header/commit/8cf14169cee5beb531a31f8d49a15fddb8c5df30
