### ISSUE TITLE
Brand switching and  brands account doesn't work

### ISSUE THREAD

**Issue by DmitriyNoa** [zalando-incubator/solution-center-header#22]
When i try to switch brand in solution-center-header drop down, it uses relative url and takes me to  frontend-stage.codebrewers.zalan.do/brands instead of redirecting to solution center brands page.

Same thing happens when i try to see brand information. It redirects me to frontend-stage.codebrewers.zalan.do/brands/49.

**Comment by dami-gg** [comment]
Have you set the correct value for the solution-center-url parameter of the directive?

**Comment by cjhowald** [comment]
Are you still seeing this issue?

**Comment by dami-gg** [comment]
@DmitriyNoa I think we can close this right?

**Comment by DmitriyNoa** [comment]
Issue is not reproducible anymore. We can close it. Thanks
