### ISSUE TITLE
Switch the order of links for 'Brand Account' and 'Switch Brand' links

### ISSUE THREAD

**Issue by sambhav-gore** [zalando-incubator/solution-center-header#31]
When clicking on the brand name in header, user is most likely looking for changing to another brand. Put the 'Switch Brand' link as the first item.

**Comment by sambhav-gore** [comment]
![switch links](https://cloud.githubusercontent.com/assets/11697969/15749112/93f2b374-28e1-11e6-9bf3-9ad940a55292.png)

**Comment by cjhowald** [comment]
I like it, but we should check with UX that Switch Brand is the more likely expected task.

**Comment by sambhav-gore** [comment]
@cjhowald this is coming from UX only. Reported  by Gloria.
