### ISSUE TITLE
User Menu Hides for User without Last Name

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-header#32]
If a user is created without a last name (should not be possible) or only a first name is passed in to the header, the user menu does not appear and the user cannot log out. We should be more flexible.

Suggestions:
- Show first and/or last name if we only have either.
- Show the user icon if no user name, so the user menu is still functional.

**Comment by dami-gg** [comment]
Both seem valid to me but I'd prefer the latter, since the former may look to the user like something is broken depending on what's shown in there, whereas showing only the icon is still nice to the eye

**Comment by gabrielhl** [comment]
Both are valid indeed - basically it comes down to "display whatever information is available, or none if none is available". And keep it functioning by always showing the icon.

**Comment by gregdeane** [comment]
My two cents:
- If only the first name OR last name exist, show just the icon.
- If both the first name AND last name exist, show the name and icon.

**Comment by dami-gg** [comment]
Your second bullet is out of question :D With this we just want to fix that corner case of missing of part of the name ;)

**Comment by gregdeane** [comment]
👍

**Comment by cjhowald** [comment]
To be clear, I was proposing both bullets, not a choice. 

The second bullet is necessary to fix the bug. The first is optional but I think it would be good to show what we have of the name even if it is not complete. Or perhaps we show first name if that's all we have, but just the icon if we only have the last name?

**Comment by gregdeane** [comment]
@cjhowald That's what my point was leaning toward. I didn't think showing just the last name was appropriate.

If we have at least a first name, show the first name and the icon.
If we don't have a first name (or we don't have a first and last name), show just the icon.

**Comment by cjhowald** [comment]
@gregdeane Exactly what I was thinking.

**Comment by dami-gg** [comment]
I've implemented this but had the doubt about whether we still need to support users having a name (vm.user.name) e.g. "Chuck Norris" and not divided into vm.user.firstName = "Chuck" and vm.user.lastName = "Norris" like it was before:

vm.username = (vm.user.firstName && vm.user.lastName) ? vm.user.firstName + " " + vm.user.lastName : vm.user.name;

@mrac @DmitriyNoa are you both supporting the new user naming format dividing it into first and last name and can I then get rid of that option?

**Comment by DmitriyNoa** [comment]
We don't support it. CMS uses user object that is stored in a cookies with name solutionCenter-user. So if it contains proper format, i can see firstName and secondName there (no name property), you can do it.

**Comment by mrac** [comment]
@dami-gg we don't depend on these User properties: name,firstName,lastName
