### ISSUE TITLE
Update logos, update favicons for retina and add to home screen

### ISSUE THREAD

**Issue by gabrielhl** [zalando-incubator/solution-center-header#34]
1. The orange in the current logos doesn't have the correct RGB value. This is because of a color conversion error, as the old logo we had was for print in CMYK format. 
-- New logo files: [zalando-logo-svg-20160613.zip](https://github.com/zalando-incubator/solution-center-header/files/311790/zalando-logo-svg-20160613.zip)

2. Our current favicon is pixelated in Retina Screen and we don't have the files for things like mobile Add to Home Screen, Windows Tiles, etc.
-- New icon files including .ico with multiple size resources: [zalando-favicons-20160613.zip](https://github.com/zalando-incubator/solution-center-header/files/311798/zalando-favicons-20160613.zip)

**Comment by gabrielhl** [comment]
More info on favicons and touch-icons here: https://github.com/audreyr/favicon-cheat-sheet#the-html

**Comment by sambhav-gore** [comment]
@gabrielhl I have updated the logo for the header which comes from s3 URI. to change the favicon we need to do it in the solution center app. I will create a jira ticket for it .
