### ISSUE TITLE
Brand Switcher has no hover effect

### ISSUE THREAD

**Issue by gabrielhl** [zalando-incubator/solution-center-header#35]
Brand Switcher has no hover effect. During user testing, some users had difficulties understanding this was clickable. We should add a hover effect.

**Comment by cjhowald** [comment]
@gabrielhl What is your recommendation for the hover effect? 

Orange text color to match the user menu to its right:
![image](https://cloud.githubusercontent.com/assets/14326547/16143428/0df9ea34-346d-11e6-8465-fe1c370cb897.png)

Blue to match the product select:
![image](https://cloud.githubusercontent.com/assets/14326547/16143441/1c9bf60e-346d-11e6-96bd-4a0340712b98.png)

Or something else?

**Comment by gabrielhl** [comment]
Hi, I think for the sake of simplicity, orange. I have a local branch with
this and other fixes implemented but I think I don't have enough privileges
to push it. Let's talk later.

On Friday, 17 June 2016, Colin Howald <notifications@github.com> wrote:

> @gabrielhl <https://github.com/gabrielhl> What is your recommendation for
> the hover effect?
>
> Orange text color to match the user menu to its right:
> [image: image]
> <https://cloud.githubusercontent.com/assets/14326547/16143428/0df9ea34-346d-11e6-8465-fe1c370cb897.png>
>
> Blue to match the product select:
> [image: image]
> <https://cloud.githubusercontent.com/assets/14326547/16143441/1c9bf60e-346d-11e6-96bd-4a0340712b98.png>
>
> Or something else?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zalando-incubator/solution-center-header/issues/35#issuecomment-226699087>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAB5Ou8am5Ev1mvB2BOvBvt3x_XFE8hWks5qMkttgaJpZM4I3cJi>
> .
>


-- 

Gabriel Lovato
Visual Designer / Brand Solutions
Zalando SE

POSTAL ADDRESS
Zalando SE
11501 Berlin

OFFICE
Zalando SE
Mollstraße 1
10178 Berlin
Germany

Fax: +493027594693
Email: gabriel.lovato@zalando.de
Web: corporate.zalando.de
Jobs: jobs.zalando.de

Zalando SE, Tamara-Danz-Straße 1, 10243 Berlin
Company registration: Amtsgericht Charlottenburg, HRB 158855 B
Tax ID: 29/560/00596 * VAT registration number: DE 260543043
Management Board: Robert Gentz, David Schneider, Rubin Ritter
Chairperson of the Supervisory Board: Cristina Stenbeck
Registered office: Berlin

**Comment by cjhowald** [comment]
You should be able to fork the repo and open a PR.

**Comment by dami-gg** [comment]
@gabrielhl Can you open a PR with your changes and we'll check it and merge it if it's fine?
