### ISSUE TITLE
Need to Hide Modules

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-header#52]
In some views, we want to hide the list of modules. Currently, we are passing in `[]` for modules, which accomplishes this, but also prevents the help widget from loading, since the help widget relies on modules for context.

Proposal: always pass in modules, but have a new field (e.g. `hideModules`, `hideNavigation`) to toggle the display of the navigation menu.

**Comment by cjhowald** [comment]
@dami-gg @sambhav-gore @gregdeane what do you think? Okay with this approach, or do you have another suggestion?

**Comment by sambhav-gore** [comment]
@cjhowald I like this approach.

**Comment by gregdeane** [comment]
@cjhowald I like your suggestion. `hide-modules` works for me.
