### ISSUE TITLE
Custom Nanorep Styles not Loading on Mobile

### ISSUE THREAD

**Issue by gabrielhl** [zalando-incubator/solution-center-header#54]
The Nanorep custom styles are not loading in mobile Chrome on Android 6.0 in HTC One M9

![image](https://cloud.githubusercontent.com/assets/31034/16302518/d8f9a336-394b-11e6-85a2-9c86744cf7d3.png)

**Comment by frontendherodk** [comment]
There seems to be an issue with how Nanorep is appending styles to the head. 
I've created a support ticket with them.

**Comment by cjhowald** [comment]
Fixed by nanorep with latest CSS.
