### ISSUE TITLE
Highlight Current Product

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-header#6]
The list of products does not indicate the currently active product. This is something that CMS & Analytics do in their header.

![image](https://cloud.githubusercontent.com/assets/14326547/13950332/a4cd162a-f02a-11e5-95c1-2dd3bfa44fd2.png)

**Comment by gabrielhl** [comment]
To indicate the active product, use a 3px #ff8e25 line under the current product. 

Here is an example on the Universal Header (quickly made using inspector). 
![image](https://cloud.githubusercontent.com/assets/31034/13950517/bf7aeb04-f02b-11e5-9ff1-c27b5ecd2979.png)

![image](https://cloud.githubusercontent.com/assets/31034/13950581/2d95104c-f02c-11e5-8606-5dabbb20cd89.png)
