### ISSUE TITLE
Products menu - responsive layout bug

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-header#68]
When the name of the brand is longer, the product menu layout is broken for smaller window sizes. It's already broken for just 2 products in the menu. I guess it would be more broken ;) for more products in the menu.

![screen shot 2016-07-12 at 15 03 13](https://cloud.githubusercontent.com/assets/690785/16767884/d8e4a2d8-4841-11e6-8912-3720e92a219c.png)

**Comment by gabrielhl** [comment]
@mrac What is "smaller sizes"? Below 600px the mobile menu should be shown, avoiding this problem. At what size did you notice this?

**Comment by mrac** [comment]
I noticed it at different sizes, starting from around 800px. It depends on how many products ar in the menu, and how long is the brand name.
