### ISSUE TITLE
Switch Brand option should not be shown if a user has only one brand.

### ISSUE THREAD

**Issue by sambhav-gore** [zalando-incubator/solution-center-header#86]
Steps to reproduce:

Login as a user who has only one brand access.
Click on Brand Name (top right) and then on 'Switch Brand'

It doesn't do anything since there is only one brand available for the user.

This should be shown only when there 2 or more brands available for a user.

**Comment by gregdeane** [comment]
When implementing this update, please add `data-e2e="sch-bs-toggle-name"` to the following element (highlighted in yellow):

https://github.com/zalando-incubator/solution-center-header/blob/master/src/solutioncenter.header.component.html#L43

**Comment by gregdeane** [comment]
Test steps:

See test steps in original comment (above)
