### ISSUE TITLE
Layout broken on iOS

### ISSUE THREAD

**Issue by mrac** [zalando-incubator/solution-center-header#91]
On iOS 7.1.2 (meaning: for both of our test iPhones ;) the layout is entirely broken:

**Comment by gabrielhl** [comment]
@mrac are you using the latest version of dress-code? The latest SC header needs the dress code grid to function properly.

**Comment by mrac** [comment]
@gabrielhl Yes we use dresscode 2.0.0-beta

**Comment by mrac** [comment]
I can't find ```-webkit``` prefix in flex CSS in the header. May be that's the reason, because it's required in iOS 7-8 and Safari 7-8:
http://caniuse.com/#search=flex

**Comment by sambhav-gore** [comment]
@mrac While this works fine on iOS 9, you are right that we should have the `-webkit`. 

However, this change should be done in analytics sass build (as you are using sass version of dress code and building the css yourself). 

`.dc-row` from dress code:

    .dc-row {
      display: -webkit-box;
      display: -ms-flexbox;
      display: flex;
      -ms-flex-flow: row wrap;
      flex-flow: row wrap;
    }

`.dc-row` in analytics (taken from https://content-router-integration.adventure.zalan.do/analytics/ ):

<img width="369" alt="" src="https://cloud.githubusercontent.com/assets/11697969/17773705/ecdcd456-654f-11e6-999f-f91559b0b9ef.png">


If you are using gulp, consider using `autoprefixer` in your build task to add the prefixes automatically.
Other option is to use minified version of dress code css directly which already should have all prefixes.

**Comment by mrac** [comment]
@sambhav-gore thanks! I'll try with autoprefixer and let you know the outcome :)

**Comment by mrac** [comment]
@sambhav-gore It worked with autoprefixer. I had to explicitly set ```browsers: ['iOS >= 7']``` option.
Thanks!

**Comment by sambhav-gore** [comment]
@mrac great to hear that. Closing this issue.
